# Site settings
title: this is PJ
subtitle: "Video Game Programmer"
SEOTitle: this Is PJ
header-img: img/home-header.jpg

email: #"pacojuanquiros [at] gmail [dot] com"
description: "Paco Juan Quirós. Video Game Programmer"
keyword: "Paco Juan Quirós, @_thisIsPJ, Video Game, Game Programmer"
url: "https://pacojq.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Site Info

# Site Author
author:
  name             : "Paco Juan Quirós"
  avatar           : "/img/bio-photo.png" # path of avatar image, e.g. "/img/bio-photo.jpg"
  bio              : "Animation Tech Programmer<br>at **IO Interactive**."
  location         : "Barcelona, Spain"
  email            : "pacojuanquiros@gmail.com"

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  games:
    output: true
    permalink: /:collection/:path/

# Publish posts or collection documents with a future date.
future: true

# SNS settings
github_username: pacojq
twitter_username: _thisIsPJ
linkedin_username:  paco-juan-6589ba14b
mastodon_username: https://mastodon.gamedev.place/@thapj

social_links:
  - label: "Twitter"
    icon: "fab fa-fw fa-twitter-square"
    url: "https://twitter.com/_thisIsPJ"
  - label: "Mastodon"
    icon: "fab fa-fw fa-mastodon"
    url: "https://mastodon.gamedev.place/@thapj"
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/pacojq"
  - label: "Linkedin"
    icon: "fab fa-fw fa-linkedin"
    url: "https://www.linkedin.com/in/paco-juan-6589ba14b/"


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - bundle-build.bat
  - bundle-serve.bat
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - tmp
  - serve.bat
  - /docs
  - /test

anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "Video Game Programmer <br> Animation Tech @ IO Interactive"
sidebar-avatar: /img/profile.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"

